/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    zkFansContract: {
      address: "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6",
      abi: [
        {
          inputs: [{ internalType: "address", name: "initialOwner", type: "address" }],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [{ indexed: false, internalType: "string", name: "cid", type: "string" }],
          name: "ContentAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "subscriber", type: "address" },
            { indexed: true, internalType: "address", name: "profile", type: "address" },
          ],
          name: "SubscribedTo",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "from", type: "address" },
            { indexed: true, internalType: "address", name: "to", type: "address" },
          ],
          name: "SubscriptionRevoked",
          type: "event",
        },
        {
          inputs: [
            { internalType: "string", name: "_hash", type: "string" },
            { internalType: "string", name: "cid", type: "string" },
          ],
          name: "addContent",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address payable", name: "_addr", type: "address" },
            { internalType: "string", name: "_name", type: "string" },
          ],
          name: "addProfile",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "_addr", type: "address" },
            { internalType: "string", name: "_hash", type: "string" },
          ],
          name: "getContent",
          outputs: [{ internalType: "string", name: "", type: "string" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "_owner", type: "address" }],
          name: "getProfileUserName",
          outputs: [{ internalType: "string", name: "", type: "string" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "owner", type: "address" },
            { internalType: "address", name: "subscriber", type: "address" },
          ],
          name: "isSubscribedToProfile",
          outputs: [{ internalType: "bool", name: "", type: "bool" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "to", type: "address" }],
          name: "revokeSubscription",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ internalType: "address payable", name: "owner", type: "address" }],
          name: "setProfileOwner",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ internalType: "address payable", name: "_profile", type: "address" }],
          name: "subscribeToProfile",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
